//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMP_Project_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComedyEntities : DbContext
    {
        public ComedyEntities()
            : base("name=ComedyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boekingsburo> Boekingsburo { get; set; }
        public virtual DbSet<Comedian> Comedian { get; set; }
        public virtual DbSet<DatumUur> DatumUur { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventComedian> EventComedian { get; set; }
        public virtual DbSet<EventLocatie> EventLocatie { get; set; }
        public virtual DbSet<Locatie> Locatie { get; set; }
        public virtual DbSet<LocatieContact> LocatieContact { get; set; }
    }
}
