//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMP_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatumUur
    {
        public int id { get; set; }
        public int eventId { get; set; }
        public System.DateTime datumTijdstip { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
