//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMP_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.DatumUur = new HashSet<DatumUur>();
            this.EventComedian = new HashSet<EventComedian>();
            this.EventLocatie = new HashSet<EventLocatie>();
        }
    
        public int id { get; set; }
        public string naam { get; set; }
        public Nullable<bool> rolstoel { get; set; }
        public bool kaartenVrij { get; set; }
        public Nullable<bool> cafeSetting { get; set; }
        public Nullable<decimal> prijs { get; set; }
        public string website { get; set; }
        public string leeftijd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatumUur> DatumUur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventComedian> EventComedian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventLocatie> EventLocatie { get; set; }
    }
}
