//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMP_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocatieContact
    {
        public int id { get; set; }
        public string naam { get; set; }
        public string voornaam { get; set; }
        public string loginName { get; set; }
        public string loginPassword { get; set; }
        public string telefoonNummer { get; set; }
        public int locatieId { get; set; }
    
        public virtual Locatie Locatie { get; set; }
    }
}
